language: java
jdk:
  - oraclejdk8
script:
  - "./mvnw clean install -B"
deploy:
  provider: heroku
  api_key:
    secure: GMqbHYnaTTnlYv+AQKBrIR+wrUt+3e4hzyjvdm+XO1xZSfIXLWGhwuZUngfhdNlVIqOrcCo0P1neBMwH0y7/+zqqZiWQ3bCuM2MDvfxR8DMLaJ7omCBpvypAN3Z32OfuMQMI8D7WXtlCLvKx997AwAfxpkStYzIO8ijmQ+2toa78nenBIo2C/rRb5OO09UYqRPEAryvEhqzFFfb4mpIPVLUEy9foo7vY3u3Owx7eV1I71xi/5N28+R61Rz8QImzED/N0Fw+NrAylIVqtO1/yNI3iEDh0xqUekDCuGMfKeUfhdFYD904rYVUg1FbRnsPw0qiOsMU8t0OHCYvaCdLXP8GT+HHowNGPfQ8rNfpj2v9wGmLc3K9/78WP728oH/OBG4saWdOAISBybzgzxZzvmVei0pqq6E0QnR9Uct0KxxiHsLRIWkHd7q8BUlpCsgEb6WUTyE7m2Ozv2HAU8uMKdB9OQTQyUS0mxpc/qMpsdKl5I6fOeQWHNYsWpWfRSaATJ2IRfi/3103KgqVzKsHk+4K8lCJxVtHRM543jrA4smpu+MNo5xmna+++Q6wSG+I4TRcn0YHChRoN+3WHVSCv0JjpGdZmmZ0KhshabKVBAfK2pn4hDCN2RbyTK33hVMneNgRddCJtsE0JrIP06fjEY+MB/wZ3rg+MCALMQa5DCzs=
  app: obscure-mesa-76333
